version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    image: clip-web
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "3s"
    tty: true
    ports:
      - "8080:8080"
    volumes:
    - "${DOCKER_WEB_VOLUME:-./public:/app/public}"
