#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

DC="${DC:-exec}"

# If we're running in CI we need to disable TTY allocation for docker-compose
# commands that enable it by default, such as exec and run.
TTY=""
if [[ ! -t 1 ]]; then
  TTY="-T"
fi

# -----------------------------------------------------------------------------
# Helper functions start with _ and aren't listed in this script's help menu.
# -----------------------------------------------------------------------------

function _dc {
  docker-compose "${DC}" ${TTY} "${@}"
}

function _build_run_down {
  docker-compose build
  docker-compose run ${TTY} "${@}"
  docker-compose down
}

# -----------------------------------------------------------------------------

function cmd {
  # Run any command you want in the web container
  _dc app "${@}"
}

function flask {
  # Run any Flask commands
  cmd flask "${@}"
}

function lint:dockerfile {
  # Lint Dockerfile
  docker container run --rm -i \
    hadolint/hadolint hadolint --ignore DL3008 --ignore DL3013 --ignore DL3009 --ignore DL3042 --ignore DL3015 "${@}" - < Dockerfile
}

function lint {
  # Lint Python code
  cmd flake8 "${@}"
}

function format {
  # Format Python code
  cmd black . "${@}"
}

function test {
  # Run test suite
  cmd pytest test/ "${@}"
}

function test:coverage {
  # Get test coverage
  cmd pytest --cov test/ --cov-report term-missing "${@}"
}

function shell {
  # Start a shell session in the web container
  cmd bash "${@}"
}



function clean {
  # Remove cache and other machine generates files
  rm -rf public/*.* public/js public/css public/images public/fonts \
    .pytest_cache/ .coverage celerybeat-schedule

  touch public/.keep
}

function ci:install-deps {
  # Install Continuous Integration (CI) dependencies
  sudo apt-get install -y curl shellcheck
  sudo curl \
    -L https://raw.githubusercontent.com/nickjj/wait-until/v0.2.0/wait-until \
    -o /usr/local/bin/wait-until && sudo chmod +x /usr/local/bin/wait-until
}

function ci:test {
  # Execute Continuous Integration (CI) pipeline
  #
  # It's expected that your CI environment has these tools available:
  #   - https://github.com/koalaman/shellcheck
  
  shellcheck run bin/*
  lint:dockerfile "${@}"
  docker-compose build
  docker-compose up -d

  # shellcheck disable=SC1091
  . .env
  lint "${@}"
  format --check
  test "${@}"
}
function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}


TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
